# tpm setup ---------------------------------------------------

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin '~/.config/tmux/plugins/tokyo-night-tmux'

# theme -------------------------------------------------------

set -g @tokyo-night-tmux_theme night
set -g @tokyo-night-tmux_transparent 1

# disable widgets ---------------------------------------------

set -g @tokyo-night-tmux_show_datetime 0
set -g @tokyo-night-tmux_show_music 0
set -g @tokyo-night-tmux_show_netspeed 0
set -g @tokyo-night-tmux_show_path 0
set -g @tokyo-night-tmux_show_battery_widget 0
set -g @tokyo-night-tmux_show_hostname 0

# icons -------------------------------------------------------

set -g @tokyo-night-tmux_terminal_icon 
set -g @tokyo-night-tmux_active_terminal_icon 

# load tpm ----------------------------------------------------

run '~/.tmux/plugins/tpm/tpm'

# status bar padding ------------------------------------------

set -Fg 'status-format[1]' '#{status-format[0]}'
set -g 'status-format[0]' ''
set -g status 2

# escape time -------------------------------------------------

set -s escape-time 0

# keybinds ----------------------------------------------------

set -g prefix M-e
unbind C-b

bind n new-window
bind m new-window -c "#{pane_current_path}"
bind l next-window
bind h previous-window
bind , new-session
bind c kill-window
bind [ swap-window -t -1 \; previous-window
bind ] swap-window -t +1 \; next-window

bind-key ';' switch-client -T jump
bind-key -T jump 0 select-window -t 0
bind-key -T jump 1 select-window -t 1
bind-key -T jump 2 select-window -t 2
bind-key -T jump 3 select-window -t 3
bind-key -T jump 4 select-window -t 4
bind-key -T jump 5 select-window -t 5
bind-key -T jump 6 select-window -t 6
bind-key -T jump 7 select-window -t 7
bind-key -T jump 8 select-window -t 8
bind-key -T jump 9 select-window -t 9
