# Device rules
monitor.alsa.rules = [
  {
    # UMC22
    matches = [
      {
        device.name = "alsa_card.usb-Burr-Brown_from_TI_USB_Audio_CODEC*"
      }
    ]
    actions = {
      update-props = {
        device.profile          = "pro-audio",
        api.alsa.period-num     = 3,
        api.alsa.period-size    = 256,
        audio.rate              = 96000,
        audio.allowed-rates     = "44100,48000,88200,96000",
        api.alsa.disable-batch  = false,
        api.alsa.use-chmap      = false,
        api.alsa.multirate      = true
      }
    }
  }
]
