general {
    lock_cmd = playerctl --all-players pause; pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

listener {
	event = sw_close
	on_event = ~/.config/hypr/scripts/check_clamshell.sh
}

listener {
    timeout = 600
    on-timeout = brightnessctl -s set 10
    on-resume = brightnessctl -r
}

listener {
    timeout = 1200
    on-timeout = systemctl suspend 
}
